// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package complexp

import (
	"github.com/conduitio/conduit-commons/config"
)

func (processorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		"field": {
			Default:     "",
			Description: "Field is the target field that will be set.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationExclusion{List: []string{".Position"}},
			},
		},
		"threshold": {
			Default:     "",
			Description: "Threshold is the threshold for filtering the record.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationGreaterThan{V: 0},
			},
		},
	}
}
